# Generated by Django 2.2.4 on 2021-04-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0002_auto_20210413_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=15),
        ),
    ]
