# Generated by Django 2.2.4 on 2021-04-15 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0005_auto_20210413_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectroutes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gmaps.Route')),
            ],
        ),
    ]
