# Generated by Django 2.2.4 on 2021-04-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0007_showbus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showbus',
            name='showbuses',
        ),
    ]
