# Generated by Django 2.2.4 on 2021-04-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0008_remove_showbus_showbuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroutes',
            name='selectroutes',
        ),
        migrations.DeleteModel(
            name='Showbus',
        ),
        migrations.DeleteModel(
            name='Showroutes',
        ),
    ]
