# Generated by Django 2.2.4 on 2021-04-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0009_auto_20210415_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='routeno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdetails',
            name='selectroute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='gmaps.Route'),
        ),
    ]
