# Generated by Django 2.2.4 on 2021-04-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0010_auto_20210422_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetails',
            name='busNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='routeno',
            field=models.IntegerField(null=True),
        ),
    ]
