# Generated by Django 2.2.4 on 2021-05-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0012_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='mobile',
            field=models.CharField(default='', max_length=20),
        ),
    ]
