# Generated by Django 2.2.4 on 2021-06-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0013_registration_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('busno', models.CharField(max_length=20)),
                ('complaints', models.CharField(max_length=100)),
            ],
        ),
    ]
