# Generated by Django 2.2.4 on 2021-06-10 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0015_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
